[@ww.label name='groupingLabel' label='Grouping Label' /]
[@ww.checkbox name='groupingLabelDelete' label='Grouping Label' /]
[@ww.label name='expireLabel' label='Expire Label' /]
[@ww.label name='labelsToRetain' label='Number of Labeled Builds to Retain' /]
[@ww.label name='labelsToIgnore' label='Labels that will be ignored for processing' /]
